# Generated by Django 5.2.5 on 2025-09-05 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keywords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='searchjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='searchresultlink',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
