# Generated by Django 5.2.5 on 2025-09-05 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_keyword_user_alter_searchjob_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresultlink',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='api.searchjob'),
        ),
    ]
