# Generated by Django 5.2.5 on 2025-09-09 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_projectfolder_keyword_folder_searchjob_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresultlink',
            name='depth',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchresultlink',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.searchresultlink'),
        ),
    ]
